### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [NFJones/genpybb#5]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 2019.11. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary pipoe -w /tmp/ext pipoe==2019.11
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting pipoe==2019.11
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/7c9/1c8440ed8390c/pipoe-2019.11.tar.gz (8.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-d2cva9aw/pipoe/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-d2cva9aw/pipoe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-d2cva9aw/pipoe/pip-egg-info
         cwd: /tmp/pip-wheel-d2cva9aw/pipoe/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-d2cva9aw/pipoe/setup.py", line 13, in <module>
        with open("requirements.txt", "r") as infile:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by NFJones** [comment]
Ah thanks for filing an issue for this! I'll get a fix out soon.
